name: Nodequery

on:
  push:
    branches: [ nodequery ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands:  npm install && npm run build && wrangler pages project create ${GITHUB_REF_NAME}  --production-branch ${GITHUB_REF_NAME} || true
          command: pages publish dist --project-name=${GITHUB_REF_NAME}